services:
  api:
    container_name: nestjs
    image: node:krypton-alpine3.23
    working_dir: /srv/api
    command: sh -c "yarn install && yarn run start"
    user: 1000:1000
    env_file:
      - .env
    volumes:
      - .:/srv/api
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mysql:8.0.19
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: proyecto
    ports:
      - 3306:3306